services:
  api_server:
    build:
      context: .
    container_name: api_server
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/hotel_db
    volumes:
      - .:/app
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3307:3306" # Change the port to avoid conflict with local MySQL
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hotel_db