name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: hotel_db
        ports:
          - 3307:3306

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies in root directory
      - name: Install dependencies in root
        run: npm install

      # Install dependencies in hotel-management directory
      - name: Install dependencies in hotel-management
        working-directory: ./hotel-management
        run: npm install

      # Run Jest unit tests in hotel-management
      - name: Run unit tests in hotel-management
        working-directory: ./hotel-management
        run: npm run test

      # Test docker-compose version
      - name: Test docker-compose version
        run: docker-compose --version

      # Run integration tests (if needed)
      - name: Run integration tests
        env:
          DATABASE_URL: mysql://root:password@mysql:3306/hotel_db
        run: |
          docker-compose up -d
          npm run test:integration

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/line-backend:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/line-backend:latest
